### ISSUE TITLE
Special characters in docker hub password prevents wercker from downloading containers

### ISSUE THREAD

**Issue by manchuck** [wercker/wercker#169] opened 2016-05-19 18:54 UTC
I was having a hard time getting a build to start.  It kept failing on pulling down a private container from docker hub.  After I changed my password to no longer have special characters, app.wercker.com was able to pull down the container. 

In my password I had "#", "+", and ",".  If I had to guess, the # was causing an issue as that is the comment character used for YAML

**Comment by faiq** [comment] 2016-05-19 19:22
dupe of #158 - with a little more insight

**Closed by faiq** 2016-05-19 19:22 UTC
