### ISSUE TITLE
wercker cuts environment variables if they contain # 

### ISSUE THREAD

**Issue by SandraKriemann** [wercker/wercker#173] opened 2016-05-25 14:27 UTC
if your environment variable, e.g. a password contains a symbol like '#' wercker is cutting your passwort starting with the # till the end. so if you’re having a password set like ‚123#abc‘ it becomes ‚123‘ what obviously leads to a 401 at the end of the day.

**Comment by davegri** [comment] 2016-05-25 14:28
Duplicate of #158

**Closed by davegri** 2016-05-25 14:28 UTC
