### ISSUE TITLE
Support running the pipeline as a different user

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#28] opened 2016-02-02 21:56 UTC
_From @hatchan on July 29, 2015 16:0_

See uservoice ticket 2870

_Copied from original issue: wercker/sentcli#529_

**Comment by sekka1** [comment] 2017-01-06 00:50
+1  would be a good thing to have

**Comment by hatchan** [comment] 2017-08-30 07:54
Duplicate of https://github.com/wercker/wercker/issues/229

**Closed by hatchan** 2017-08-30 07:54 UTC
Labels: enhancement, normal
