### ISSUE TITLE
internal/shell Unable to sync environment

### ISSUE THREAD

**Issue by mbrevda** [wercker/wercker#114] opened 2016-03-15 14:43 UTC
After about five minutes of hanging, `internal/shell` responds with:

```
WARNING Unable to sync environment Error=Command timed out after no response
```

**Comment by JeanMertz** [comment] 2016-04-09 21:46
I'm getting the same issue with the `internal/docker-push` step:

```
--> Running step: docker push
WARNING Unable to sync environment Error=Command timed out after no response
Pushing image for tag  4fbe73c
```

After that, the step continues and succeeds as expected. It _does_ indeed cause a long timeout, and thus a long step duration.

**Comment by JeanMertz** [comment] 2016-06-14 10:20
ping @hatchan any clue about this one? A colleague of mine just had this as well (using docker-machine on OS X)

**Comment by hatchan** [comment] 2016-06-17 08:52
This could be caused by a container which doesn't support the `env --null` command. In these cases you can disable the sync env step by adding the `disable-sync` property to the `docker-push` step. More info: http://devcenter.wercker.com/docs/faq/alpine-faq.html#i-receive-the-unable-to-sync-environment-when-using-docker-push-on-alpine

**Comment by Tonnu** [comment] 2016-07-05 13:43
Closing this for now. If @hatchan's comment didn't help you out I'll re-open.

**Closed by Tonnu** 2016-07-05 13:43 UTC

**Comment by djMax** [comment] 2016-10-06 14:22
This is a crappy option... Basically it means you can't use generated env vars on alpine images. To me that's not a fix for the bug.
