### ISSUE TITLE
wercker should fail when pipeline not found in yaml

### ISSUE THREAD

**Issue by flenter** [wercker/wercker#120] opened 2016-03-18 13:11 UTC
Setup environment fails without any relevant information when executing a workflow.

Example output:
![screen shot 2016-03-18 at 14 11 06](https://cloud.githubusercontent.com/assets/473804/13878687/4dae6200-ed13-11e5-929a-cf16625458f4.png)

note: this may be a workflow specific issue

**Comment by hatchan** [comment] 2016-03-18 13:13
duplicate of #94

**Closed** 2016-03-18 14:33 UTC
Labels: bug
